bot:
  abi_migration_branches: [v9.3.0]
build_platform: {osx_arm64: osx_64}
conda_forge_output_validation: true
provider: {linux_aarch64: default, linux_ppc64le: default}
conda_build:
  pkg_format: '2'
test: native_and_emulated
